INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (1,NULL,NULL,'Drivers',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (2,NULL,NULL,'Clients',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (3,NULL,NULL,'Orders',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (4,NULL,NULL,'Cars',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (5,NULL,NULL,'Orders_log',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (6,NULL,NULL,'Drivers_log',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (7,NULL,NULL,'Routes',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (8,NULL,NULL,'Order_status',NULL);
INSERT INTO OBJTYPE (OBJECT_TYPE_ID,PARENT_ID,CODE,NAME,DESCRIPTION) VALUES (9,NULL,NULL,'Driver_status',NULL);

INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (1,1,NULL,NULL,'Last_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (2,1,NULL,NULL,'First_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (3,1,NULL,NULL,'Middle_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (4,1,NULL,NULL,'Phone_number');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (5,1,NULL,NULL,'Email');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (6,1,NULL,NULL,'Hir_date');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (7,1,NULL,NULL,'Experience');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (8,1,NULL,NULL,'Rating');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (9,1,9,NULL,'Status');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (10,1,NULL,NULL,'Unbun_date');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (11,2,NULL,NULL,'Last_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (12,2,NULL,NULL,'First_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (13,2,NULL,NULL,'Middle_name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (14,2,NULL,NULL,'Phone_number');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (15,2,NULL,NULL,'Points');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (16,3,2,NULL,'Client_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (17,3,1,NULL,'Driver_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (18,3,8,NULL,'Status');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (19,3,NULL,NULL,'Cost');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (20,3,NULL,NULL,'Distance');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (21,3,NULL,NULL,'Driver_rating');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (22,3,NULL,NULL,'Driver_memo');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (23,4,NULL,NULL,'Name');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (24,4,NULL,NULL,'Model_type');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (25,4,NULL,NULL,'Prodaction_date');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (26,4,NULL,NULL,'Seats_count');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (27,4,NULL,NULL,'Child_seat');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (28,4,1,NULL,'Driver_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (29,4,NULL,NULL,'State_number');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (30,5,3,NULL,'Order_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (31,5,NULL,NULL,'Status');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (32,5,NULL,NULL,'Timestamp');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (33,6,1,NULL,'Driver_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (34,6,NULL,NULL,'Status');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (35,6,NULL,NULL,'Timestamp');


INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (36,7,3,NULL,'Order_id');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (37,7,NULL,NULL,'Check_point');
INSERT INTO ATTRTYPE (ATTR_ID,OBJECT_TYPE_ID,OBJECT_TYPE_ID_REF,CODE,NAME) VALUES (38,7,NULL,NULL,'Show_order');


INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (1,NULL,8,'new',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (2,NULL,8,'accepted',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (3,NULL,8,'performed',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (4,NULL,8,'performing',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (5,NULL,8,'canceled',NULL);

INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (6,NULL,9,'approval',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (7,NULL,9,'off duty',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (8,NULL,9,'free',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (9,NULL,9,'on call',NULL);
INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (10,NULL,9,'perform order',NULL);



/*������ �������� ��� �������� ������ �������*/

INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (11,NULL,1,'Driver Natasha',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (1,11,'Natasha',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (2,11,'Stavitskaya',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (3,11,'Nick',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (4,11,'0631486586',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (5,11,'Natasha@gmail.com',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (6,11,NULL,'01/08/2017');
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (7,11,4,NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (8,11,10,NULL);



INSERT INTO OBJECTS (OBJECT_ID,PARENT_ID,OBJECT_TYPE_ID,NAME,DESCRIPTION) VALUES (12,NULL,1,'Driver Vadim',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (1,12,'Natasha',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (2,12,'Stavitskaya',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (3,12,'Nick',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (4,12,'0631486586',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (5,12,'Natasha@gmail.com',NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (6,12,NULL,'01/08/2017');
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (7,12,4,NULL);
INSERT INTO ATTRIBUTES(ATTR_ID,OBJECT_ID,VALUE,DATE_VALUE) VALUES (8,12,10,NULL);


HashMap<Integer, String> map = new HashMap<>();
map.put(1, 'Natasha');
map.put(2, 'Stavitskaya');
map.put(3, 'Nick');
map.put(4, '0631486586');
map.put(5, 'Natasha@gmail.com');
map.put(6, '01/08/2017');


map.put(1, 'Driver Vadim');




INSERT INTO OBJREFERENCE (ATTR_ID,OBJECT_ID,REFERENCE) VALUES (9,11,8);


Select -1 attr_id,'NAME' as "Name",NAME value  from objects where objects.object_id = 11
UNION
Select -2 attr_id,'OBJECT_TYPE_ID' as "Name",TO_CHAR(OBJECT_TYPE_ID) value from objects where objects.object_id = 11
UNION
Select -3 attr_id,'PARENT_ID' as "Name",TO_CHAR(PARENT_ID) value from objects where objects.object_id = 11
UNION
Select attributes.ATTR_ID attr_id,attrtype.name as "Name",nvl(attributes.value,attributes.date_value) value
from attributes,attrtype,objects
where objects.object_id = 11
AND attributes.object_id = objects.object_id
AND (attrtype.OBJECT_TYPE_ID = Objects.OBJECT_TYPE_ID OR attrtype.OBJECT_TYPE_ID = Objects.Parent_id)
AND attrtype.ATTR_ID = attributes.ATTR_ID
UNION
select OBJREFERENCE.ATTR_ID attr_id,attrtype.name as "Name",Objects.NAME  value
from OBJREFERENCE,attrtype,Objects, Objects O 
where O.OBJECT_ID = 11
AND OBJREFERENCE.OBJECT_ID  = O.OBJECT_ID
AND OBJREFERENCE.ATTR_ID =attrtype.ATTR_ID
AND OBJREFERENCE.REFERENCE = Objects.OBJECT_ID 
AND (attrtype.OBJECT_TYPE_ID = O.OBJECT_TYPE_ID OR attrtype.OBJECT_TYPE_ID = O.Parent_id);






