package com.netcracker.project.study.vaadin.test.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.spring.annotation.SpringUI;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.CustomComponent;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
@SpringUI(path = "")
public class DriversList extends CustomComponent {

    public DriversList() {
        Design.read(this);
    }
}
